### ISSUE TITLE
Phase II: Finish Manual FERC-EIA Map of Top 10 Utilities

### ISSUE THREAD

**Issue by aesharpe** [catalyst-cooperative/rmi-ferc1-eia#175]
During Phase I (#113), we made an effort to map as many of the top 10 utilities as possible. The mapping process includes a first pass and a second QA/QC check. We completed most of the first pass. 

As of the start of this epic, our progress mapping is as follows. The utilities are listed in order of importance: 

```[tasklist]
### **Duke**: 
   - [x] 1st pass
   - [x] 2nd pass
   - [x] Validation
   - [x] Integration: #2379 (pudl repo: https://github.com/catalyst-cooperative/pudl/pull/2379)
```
Final spreadsheet used for integration: [Duke_fix_FERC1-EIA_overrides.xlsx](https://github.com/catalyst-cooperative/rmi-ferc1-eia/files/11206051/Duke_fix_FERC1-EIA_overrides.xlsx)

```[tasklist]
### **Entergy**:
- [x] 1st pass: https://github.com/catalyst-cooperative/rmi-ferc1-eia/issues/277
- [x] 2nd pass / Validation: https://github.com/catalyst-cooperative/rmi-ferc1-eia/issues/278
- [x] Integration: https://github.com/catalyst-cooperative/rmi-ferc1-eia/issues/279
```
Final spreadsheet used for integration: [Entergy_FERC1-EIA_overrides.xlsx](https://github.com/catalyst-cooperative/rmi-ferc1-eia/files/11206056/Entergy_FERC1-EIA_overrides.xlsx)

```[tasklist]
### **BHE**:
   - [x] 1st pass:
   - [x] 2nd pass
   - [x] Validation
   - [x] Integration: #2347 (pudl repo, part of this PR but no individual PR https://github.com/catalyst-cooperative/pudl/pull/2347) 
```
Final spreadsheet used for integration: [BHE_FERC1-EIA_overrides.xlsx](https://github.com/catalyst-cooperative/rmi-ferc1-eia/files/11206060/BHE_FERC1-EIA_overrides.xlsx)

```[tasklist]
### **Southern**: 
   - [x] 1st pass
   - [x] 2nd pass
   - [x] Validation
   - [x] Integration: #2347 (pudl repo, part of this PR but no individual PR https://github.com/catalyst-cooperative/pudl/pull/2347)
```
Final spreadsheet used for integration: [Southern_FERC1-EIA_overrides.xlsx](https://github.com/catalyst-cooperative/rmi-ferc1-eia/files/11206062/Southern_FERC1-EIA_overrides.xlsx)

```[tasklist]
### **Dominion**:
   - [x] 1st pass
   - [x] 2nd pass
   - [x] Validation
   - [x] Integration #247 
```
Final spreadsheet used for integration: [Dominion_FERC1-EIA_overrides.xlsx](https://github.com/catalyst-cooperative/rmi-ferc1-eia/files/11206064/Dominion_FERC1-EIA_overrides.xlsx)

```[tasklist]
### **NextEra**:
   - [x] 1st pass
   - [x] 2nd pass (in progress):
   - [x] Validation: #262 
   - [x] Integration: #274 
```
Final spreadsheet used for integration: [NextEra_FERC1-EIA_overrides.xlsx](https://github.com/catalyst-cooperative/rmi-ferc1-eia/files/11206065/NextEra_FERC1-EIA_overrides.xlsx)

```[tasklist]
### **Xcel**: 
   - [x] 1st pass
   - [x] 2nd pass
   - [x] Validation: #260 
   - [x] Integration: #280 (pudl repo: https://github.com/catalyst-cooperative/pudl/pull/2405)
```
Final spreadsheet used for integration: [Xcel_FERC1-EIA_overrides.xlsx](https://github.com/catalyst-cooperative/rmi-ferc1-eia/files/11206067/Xcel_FERC1-EIA_overrides.xlsx)

```[tasklist]
### **Evergy**:
   - [x] 1st pass
   - [x] 2nd pass: 
   - [x] Validation: #261 
   - [x] Integration #273 
```
Final spreadsheet used for integration: [Evergy_FERC1-EIA_overrides.xlsx](https://github.com/catalyst-cooperative/rmi-ferc1-eia/files/11206069/Evergy_FERC1-EIA_overrides.xlsx)

```[tasklist]
### **IdaCorp**:
   - [x] 1st pass
   - [x] 2nd pass
   - [x] Validation: #259 
   - [x] Integration: #267 
```
Final spreadsheet used for integration: [IDACORP_FERC1-EIA_overrides.xlsx](https://github.com/catalyst-cooperative/rmi-ferc1-eia/files/11206070/IDACORP_FERC1-EIA_overrides.xlsx)

### Pending RMI Need
- **AEP**: 
   - [ ] 1st pass
   - [ ] 2nd pass
   - [ ] Validation

Phase II will cover the rest of the mapping, both 1st and 2nd passes. This work is done in tandem with folks at RMI.

The mapping spreadsheets for each utility were created using the `make_overrides.ipynb` in the `rmi-ferc1-eia` repo. All the spreadsheets for the relevant utilities have been created and are stored in the RMI sharepoint folder called [FERC-EIA Data QC](https://rockmtnins.sharepoint.com/sites/UTF/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FUTF%2FShared%20Documents%2FUtility%20Transition%20Database%2FDepreciation%2DFERC%2DEIA%20Database%2FFERC%2DEIA%20Data%20QC&viewid=3e4242bc%2Deb3b%2D45d2%2D95c5%2D4a80e3463c36). This folder has subfolders for 1st and 2nd passes. When a spreadsheet is finished with its 1st pass, it goes in the 2nd pass folder. When it's done with the 2nd pass, it goes in the final folder.

Instructions for 1st and 2nd pass mapping are [here](https://docs.google.com/document/d/1nJfmUtbSN-RT5U2Z3rJKfOIhWsRFUPNxs9NKTes0SRA/edit#).

**Comment by aesharpe** [comment]
For all intents and purposes, this issue is complete. Remaining tasks include:

### **One-to-Many**: 
   - https://github.com/catalyst-cooperative/pudl/issues/1555
   - https://github.com/catalyst-cooperative/pudl/pull/2429


### **Many-to-One**: 
   - https://github.com/catalyst-cooperative/pudl/issues/2455

**Comment by aesharpe** [comment]
closed with merge of pudl repo 2502
